feat: add support for low-cost instances
googleapis/python-spanner pull request #313
Opened 2021-04-22 00:53 UTC by zoercai

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

2021-04-22 10:17 UTC, larkee requested changes

2021-04-22 10:17 UTC, larkee commented on google/cloud/spanner_v1/client.py
>          node_count=DEFAULT_NODE_COUNT,
My understanding is that `node_count` and `processing_units` are exclusive (i.e. only one can be specified) so I would change this to `node_count=None` and add logic to set the default if neither are set and raise an error if both are set.

2021-04-22 10:17 UTC, larkee commented on google/cloud/spanner_v1/client.py
> +                                allocated to this instance.
Might be worth mentioning that you can only set either `node_count` or `processing_units`

2021-04-22 10:17 UTC, larkee commented on google/cloud/spanner_v1/instance.py
> +                instance.processing_unit = 2000
This is invalid. You can't set both `node_count` and `processing_units`. Either revert this or remove the `node_count` value.

2021-04-22 10:17 UTC, larkee commented on tests/unit/test_client.py
> +    PROCESSING_UNITS = 2000
nit: set this to 5000 so it is equivalent to `NODE_COUNT`.

2021-04-23 18:58 UTC, leahecole commented
I think it's adding me as a reviewer because of the synthtool changes in `.github/header-checker-lint.yml` and those LGTM :)

2021-04-26 07:35 UTC, larkee commented on google/cloud/spanner_v1/instance.py
> +                'Only one of node count and processing units can be set.')
nit: put the validation check before setting the default

If the validation fails then the default isn't needed.

2021-04-26 07:35 UTC, larkee commented on google/cloud/spanner_v1/instance.py
> +                        Cannot be set if processing_units is set.
nit: use `processing_units` for the docs render. Also applies to processing_units docstring below

2021-05-06 04:41 UTC, larkee reviewed
Just a couple comments to go with the proposed changes to resolve the update issue we discussed :+1:

2021-06-21 23:30 UTC, larkee approved these changes

2021-06-22 23:50 UTC, larkee commented on google/cloud/spanner_v1/instance.py
> +        :returns node_count:
nit: returns don't need a name
```suggestion
        :returns:
```

2021-06-23 23:26 UTC, merged