feat: add RPC priority support
googleapis/python-spanner pull request #324
Opened 2021-04-28 05:03 UTC by zoercai

2021-04-29 05:46 UTC, larkee requested changes
LG overall however there is some functionality missing.

First, all commit methods should support this, including `Batch.commit()`.
Secondly, we usually call commit on behalf of the user which means they will not be able to pass the options to the commit call themselves. This means we need to provide alternate ways of passing in the options. e.g.
```
database.run_in_transaction(transaction_func, request_options={"priority": "PRIORITY_LOW"})
```
```
for database.batch(request_options={"priority": "PRIORITY_MEDIUM"}) as batch:
    batch.insert(table, columns, data)
```

Additionally, you should update the PR description to give context on the feature and how it should be used. For example, it should mention that all requests are run as `PRIORITY_HIGH` by default and so this feature is to deprioritize tasks.

2021-04-30 06:42 UTC, zoercai commented on tests/system/test_system.py
> +                "api_endpoint": "staging-wrenchworks.sandbox.googleapis.com:443"
remove

2021-04-30 06:42 UTC, zoercai commented on google/cloud/spanner_v1/transaction.py
> +                (Optional) Common options for this request.
add dict option

2021-06-08 04:53 UTC, larkee commented on google/cloud/spanner_v1/session.py
> +        commit_request_options = kw.pop("commit_request_options", None)
Please add a note about this to the `kw` parameter documentation.

2021-06-08 04:53 UTC, larkee commented on google/cloud/spanner_v1/database.py
> +from google.cloud.spanner_v1.types import RequestOptions
You can import `RequestOptions` from `google.cloud.spanner_v1` so please move this to be with the other `google.cloud.spanner_v1` imports.

2021-06-08 04:53 UTC, larkee commented on google/cloud/spanner_v1/batch.py
> +from google.cloud.spanner_v1.types import RequestOptions
Move to be with other imports.

2021-06-11 04:14 UTC, larkee reviewed
Some minor docstring nits :)

2021-06-11 04:14 UTC, larkee commented on google/cloud/spanner_v1/database.py
> +                (Optional) Common options for this request.
```suggestion
                (Optional) Common options for the commit request.
```

2021-06-11 04:14 UTC, larkee commented on google/cloud/spanner_v1/database.py
> +            (Optional) Common options for this request.
```suggestion
            (Optional) Common options for the commit request.
```

2021-06-11 04:14 UTC, larkee commented on google/cloud/spanner_v1/session.py
> +                   request_options which defines the common options for requests.
nit: "commit_request_options" will be removed and used to set the request options for the commit request.

2021-06-11 06:21 UTC, larkee approved these changes

2021-06-22 05:55 UTC, merged