fix: avoid bad version of `opentelemetry-instrumentation`
googleapis/python-spanner pull request #429
Opened 2021-07-27 01:05 UTC by larkee

Version `0.23b0` of `opentelemetry-instrumentation` is causing unit tests failure relating to opentelemetry assertions. This PR updated the `google-cloud-spanner` dependency to avoid this particular version.

2021-07-27 16:27 UTC, tseaver requested changes
The main change here (in `setup.py` looks fine).

For the `testing/constraints-x.y.txt` files, the pattern in other libraries is to have the one associated with the lowest supported Python version (i.e, `testing/constraints-3.x.txt`) pin all the minimum dependencies, so that the library gets tested against them, but leave them unpinned for the higher supported versions (so that we continue to test against current versions).

2021-07-28 04:32 UTC, larkee commented
@tseaver The test pass locally with the change but the CI is still failing :confused: Any ideas? This is blocking all PRs

2021-07-28 19:08 UTC, tseaver commented
@larkee I'm puzzled.  Can  you tweak `noxfile` to show the installed version of `opentelemetry-instrumenation`, e.g.:

```python
    session.run("pip", "show", "opentelemetry-instrumentation")
```

I'm seeing this locally, *and* it fails:
```
Name: opentelemetry-instrumentation
Version: 0.23b2
Summary: Instrumentation Tools & Auto Instrumentation for OpenTelemetry Python
Home-page: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/opentelemetry-instrumentation
Author: OpenTelemetry Authors
Author-email: cncf-opentelemetry-contributors@lists.cncf.io
License: Apache-2.0
Location: /home/tseaver/projects/agendaless/Google/src/python-spanner/.nox/unit-3-9/lib/python3.9/site-packages
Requires: opentelemetry-api, wrapt
Required-by: opentelemetry-sdk
```

2021-07-28 19:09 UTC, tseaver requested changes

2021-07-28 19:09 UTC, tseaver commented on setup.py
> +        "opentelemetry-instrumentation >= 0.20b0, != 0.23b0",
```suggestion
        "opentelemetry-instrumentation >= 0.20b0, < 0.23dev",
```

2021-07-28 22:03 UTC, tseaver approved these changes

2021-07-28 22:03 UTC, merged