chore: changing default region to us-west1
googleapis/python-spanner pull request #640
Opened 2021-11-11 12:51 UTC by asthamohta

2021-11-15 01:12 UTC, larkee approved these changes

2021-11-15 03:36 UTC, larkee requested changes
The backup tests also use an additional instance with a different config:
https://github.com/googleapis/python-spanner/blob/8ca868c3b3f487c1ef4f655aedd0ac2ca449c103/tests/system/test_backup_api.py#L56
We should probably prevent that one from choosing `us-central1` for now as well.

We should also make this change for the samples:
https://github.com/googleapis/python-spanner/blob/main/samples/samples/conftest.py#L90

2021-12-21 04:52 UTC, vi3k6i5 approved these changes
LGTM

2021-12-21 05:23 UTC, larkee approved these changes

2021-12-21 05:44 UTC, merged