fix: add session.exists() check in PingingPool.get() method.
googleapis/python-spanner pull request #694
Opened 2022-03-28 07:07 UTC by vi3k6i5

PingingPool checks if session exists in `.get()` method, but right now it does the check only when

2022-03-28 07:47 UTC, asthamohta approved these changes

2022-03-28 07:55 UTC, larkee requested changes
This change means that every session will be checked before use which sounds great but the added latency defeats the purpose of the pinging pool and will slow down existing applications.

I think having logic for catching the exception in `SessionCheckout` might make more sense.

2022-03-28 17:18 UTC, beaverlyhills commented
I agree that handling exceptions in the `__exit__` blocks of all session checkout context managers is the way to go.

I would also suggest to not update the `wait_time` in `put()` method as there is no guarantee that any queries were actually performed by the caller. I wonder if that was the root cause of the issue we observed in our system, rather than Spanner server forcefully closing the session.

Callers would be responsible for handling `NotFound` exception and doing the retry with another session, which is something worth mentioning in the documentation of `PingingPool` as it does not guarantee that returned sessions are always valid.

2022-04-19 11:23 UTC, vi3k6i5 commented
@beaverlyhills @larkee : Created a separate PR with the relevant changes: https://github.com/googleapis/python-spanner/pull/718 For some reason this PR was not getting updated.

2022-04-19 11:23 UTC, closed without merging