chore: allow releases from previous major versions
googleapis/python-spanner pull request #708
Opened 2022-04-06 00:58 UTC by busunkim96

2022-04-06 18:31 UTC, parthea requested changes
Please update owlbot.py in order to persist the change

2022-04-06 22:07 UTC, busunkim96 commented
Fixed! PTAL.

2022-04-07 15:05 UTC, parthea approved these changes

2022-04-07 15:06 UTC, parthea approved these changes

2022-04-07 15:14 UTC, busunkim96 commented
Samples failures are unrelated to config change, admin merging.

2022-04-07 15:15 UTC, merged